'use strict';

/**
 * Full question bank — mirrors the frontend whitelist.js bank.
 * Used by the revision page to display question text and options.
 */
module.exports = [
  /* 0  */ { q: '¿Qué significa IC?', opts: ['Información externa','Todo lo que ocurre dentro del rol','Chat de voz','Normas del servidor'], c: 'B' },
  /* 1  */ { q: '¿Qué es OOC?', opts: ['Información dentro del rol','Tipo de sanción','Información fuera del rol','Acción ilegal'], c: 'C' },
  /* 2  */ { q: '¿Qué es MG?', opts: ['Usar info OOC en IC','Matar sin rol','Robar coches','Conducir mal'], c: 'A' },
  /* 3  */ { q: '¿Es válido usar Discord para obtener info IC?', opts: ['Sí','Solo policías','Solo mafias','No'], c: 'D' },
  /* 4  */ { q: '¿Qué es RDE?', opts: ['Robar vehículos','Interpretar entorno aunque no se vea','Matar sin rol','Tipo de bug'], c: 'B' },
  /* 5  */ { q: 'Robar delante de comisaría sin policías visibles es...', opts: ['Válido','RDE correcto','Inválido','FairPlay'], c: 'C' },
  /* 6  */ { q: '¿Qué es CK?', opts: ['Muerte total del personaje','Golpear','Inconsciencia','Desconexión'], c: 'A' },
  /* 7  */ { q: '¿Quién aprueba un CK voluntario?', opts: ['Jugador','Policía','Administrador','Nadie'], c: 'C' },
  /* 8  */ { q: '¿Qué es FairPlay?', opts: ['Evadir rol','Jugar limpio','Ganar siempre','Usar bugs'], c: 'B' },
  /* 9  */ { q: 'Usar bugs para ganar rompe el...', opts: ['CK','RDE','FairPlay','PK'], c: 'C' },
  /* 10 */ { q: '¿Qué es PK?', opts: ['Muerte total','Ban','Inconsciencia','Bug'], c: 'C' },
  /* 11 */ { q: '¿Qué pasa en PK Parcial?', opts: ['Recuerdas todo','No recuerdas nada','Muere el PJ','No recuerdas el momento'], c: 'D' },
  /* 12 */ { q: '¿Qué es PKT?', opts: ['Recordar todo','No recordar nada','Morir','Evadir rol'], c: 'B' },
  /* 13 */ { q: 'NVV significa...', opts: ['No ver vehículos','No vender','No valorar vida','No usar voz'], c: 'C' },
  /* 14 */ { q: 'Sacar arma cuando te apuntan es...', opts: ['Correcto','NVV','RDE','CJ'], c: 'B' },
  /* 15 */ { q: '¿Qué es BJ?', opts: ['Saltar para ventaja','Matar sin rol','Robar','Mentir'], c: 'A' },
  /* 16 */ { q: '¿Qué es RK?', opts: ['Robar coche','Conducir mal','Vengarte tras PK','Usar bug'], c: 'C' },
  /* 17 */ { q: '¿Qué es DM?', opts: ['Robar','Matar sin rol previo','Saltar','Huir'], c: 'B' },
  /* 18 */ { q: '¿Qué es VDM?', opts: ['Disparar','Robar','Huir','Atropellar sin rol'], c: 'D' },
  /* 19 */ { q: '¿Qué es BD?', opts: ['Bad Driving','Robar coche','Conducir mal sin rol','Saltar'], c: 'A' },
  /* 20 */ { q: '¿Un jugador recibe info por Discord y luego investiga ese sitio sin motivo IC. Qué es?', opts: ['Correcto','RDE','MG indirecto','FairPlay'], c: 'C' },
  /* 21 */ { q: '¿Estás abatido y das info por Discord. Qué es?', opts: ['RK','MG leve','BD','Ghosting'], c: 'D' },
  /* 22 */ { q: 'Cambiar historia del personaje constantemente sin rol es...', opts: ['NVV','IDP incumplido','PG','CK'], c: 'B' },
  /* 23 */ { q: 'Usar /do para expresar emociones es...', opts: ['Correcto','Depende','Incorrecto','Solo policías'], c: 'C' },
  /* 24 */ { q: 'Robar en un barrio vacío sin rolear entorno es...', opts: ['MG','CJ','RK','RDE incumplido'], c: 'D' },
  /* 25 */ { q: 'Volver tras PK a buscar al que te mató "por casualidad" es...', opts: ['Correcto','PKT','FairPlay','RK indirecto'], c: 'D' },
  /* 26 */ { q: 'AFK en medio de un secuestro provoca...', opts: ['CK','Cortar rol','RDE','BD'], c: 'B' },
  /* 27 */ { q: 'Atropellar a alguien que te apunta es...', opts: ['Defensa válida','BD','CJ','Car Kill + NVV'], c: 'D' },
  /* 28 */ { q: 'Usar un bug sin avisar es...', opts: ['Permitido','PG leve','Abuso de bugs','FairPlay'], c: 'C' },
  /* 29 */ { q: '¿Qué es PG?', opts: ['Jugar limpio','Hacer cosas irreales','Matar','Robar'], c: 'B' },
  /* 30 */ { q: 'Conducir por montaña con deportivo es...', opts: ['Correcto','BD','PG','RK'], c: 'C' },
  /* 31 */ { q: '¿Qué es AFK?', opts: ['Estar activo','Estar ausente','Matar','Saltar'], c: 'B' },
  /* 32 */ { q: '¿Qué es MK?', opts: ['Robar','Conducir','Saltar','Matar por info OOC'], c: 'D' },
  /* 33 */ { q: '¿Qué es OA?', opts: ['Abusar de objetos','Robar','Saltar','Matar'], c: 'A' },
  /* 34 */ { q: '¿Qué es CJ?', opts: ['Comprar coche','Vender coche','Robar coche sin rol','Reparar'], c: 'C' },
  /* 35 */ { q: '¿Qué es SK?', opts: ['Robar','Saltar','Curar','Matar recién conectado'], c: 'D' },
  /* 36 */ { q: '¿Qué es ZZ?', opts: ['Correr normal','Saltar','Conducir lento','Zigzag para evitar balas'], c: 'D' },
  /* 37 */ { q: '¿Para qué sirve /me?', opts: ['Hablar OOC','Describir acciones','Insultar','Reportar'], c: 'B' },
  /* 38 */ { q: '¿Es obligatorio llevar Documentación?', opts: ['No','Solo policías','Sí','Solo civiles'], c: 'C' },
  /* 39 */ { q: '¿Qué ocurre si usas información obtenida por un stream en directo para actuar IC?', opts: ['Es válido si no hablas en chat','Solo si es tu amigo','MG aunque no lo digas explícitamente','No es sancionable'], c: 'C' },
  /* 40 */ { q: '¿Un jugador te reconoce por la voz (IC) pero tú sabes que es por Discord (OOC). Qué haces?', opts: ['Ignorar completamente','Aprovecharlo','Reportar o ignorar ICmente la info','Usar la info parcialmente'], c: 'C' },
  /* 41 */ { q: '¿Estás en una persecución y tu coche queda inutilizado. Sales corriendo mientras te apuntan. Es correcto?', opts: ['Sí, siempre','No, es NVV','Solo si eres rápido','Depende del arma'], c: 'B' },
  /* 42 */ { q: '¿Qué define mejor el PowerGaming (PG)?', opts: ['Ganar siempre','Forzar acciones irreales sin dar opción a otros','Matar sin rol','Usar bugs'], c: 'B' },
  /* 43 */ { q: '¿Un policía usa la excusa de "actitud sospechosa" para cachear sin base. Qué es?', opts: ['Procedimiento válido','Rol agresivo correcto','Abuso de rol / PG','FairPlay'], c: 'C' },
  /* 44 */ { q: '¿Puedes iniciar rol hostil sin interacción previa si hay contexto IC suficiente?', opts: ['Nunca','Siempre','Sí, si el contexto lo justifica claramente','Solo policías'], c: 'C' },
  /* 45 */ { q: '¿Te disparan sin previo aviso pero había tensión previa en rol. Es DM?', opts: ['Sí siempre','No necesariamente','Sí si mueres','Depende del arma'], c: 'B' },
  /* 46 */ { q: '¿Qué es "forzar rol"?', opts: ['No rolear','Obligar resultados sin dar opción','Matar','Huir'], c: 'B' },
  /* 47 */ { q: '¿Si estás inconsciente (PK), puedes escuchar conversaciones?', opts: ['Sí','No','Solo parcialmente','Depende del rol'], c: 'B' },
  /* 48 */ { q: '¿Un jugador usa /me para acciones imposibles (ej: esquivar balas). Qué es?', opts: ['Correcto','PG','FairPlay','BJ'], c: 'B' },
  /* 49 */ { q: '¿Qué ocurre si provocas a otro jugador hasta que te ataque para "justificar" matarlo?', opts: ['Estrategia válida','FairPlay','Forzar rol / PG','RK'], c: 'C' },
  /* 50 */ { q: '¿Se puede robar sin interacción verbal previa?', opts: ['Sí siempre','No nunca','Sí, si el contexto lo permite (arma + entorno)','Solo mafias'], c: 'C' },
  /* 51 */ { q: '¿Qué es "entorno implícito"?', opts: ['Lo que ves','Lo que el juego no muestra pero existe','El mapa','Los NPC'], c: 'B' },
  /* 52 */ { q: '¿Qué ocurre si ignoras completamente el entorno en un rol?', opts: ['Nada','RDE','MG','BD'], c: 'B' },
  /* 53 */ { q: '¿Un jugador acepta rol pero luego lo ignora (no responde, no actúa). Qué es?', opts: ['AFK','Cortar rol','RK','CJ'], c: 'B' },
  /* 54 */ { q: '¿Qué pasa si usas animaciones para evitar daño constantemente?', opts: ['Estrategia','Skill','Abuso / PG','FairPlay'], c: 'C' },
  /* 55 */ { q: '¿Puedes disparar desde un lugar donde tu hitbox no es visible?', opts: ['Sí','No','Solo si es sniper','Depende'], c: 'B' },
  /* 56 */ { q: '¿Qué define mejor NVV en situaciones límite?', opts: ['No morir','Priorizar ganar sobre supervivencia realista','Disparar primero','Huir'], c: 'B' },
  /* 57 */ { q: '¿Un EMS ignora a un herido para ir a otro rol más interesante. Qué es?', opts: ['Decisión válida','Rol selectivo / mala praxis','FairPlay','MG'], c: 'B' },
  /* 58 */ { q: '¿Qué pasa si usas binds para acciones complejas instantáneas?', opts: ['Correcto','Ventaja injusta / PG','Skill','No importa'], c: 'B' },
  /* 59 */ { q: '¿Un jugador usa /do para preguntar cosas que su personaje no podría saber (ej: "tiene arma" sin inspeccionar). Qué es?', opts: ['Uso correcto','MG leve','PG','Rol válido'], c: 'B' },
  /* 60 */ { q: '¿Estás en un rol donde claramente vas a perder (rodeado, sin salida). Decides rendirte aunque podrías intentar escapar con suerte. ¿Es correcto?', opts: ['No, debes intentar escapar siempre','Sí, valorar la vida es correcto','Solo si eres civil','Depende del arma'], c: 'B' },
  /* 61 */ { q: '¿Un jugador inicia rol agresivo sin dar tiempo de reacción (dispara inmediatamente tras hablar 1 segundo). Qué es?', opts: ['DM','Rol rápido','FairPlay','PG'], c: 'A' },
  /* 62 */ { q: '¿Qué ocurre si utilizas animaciones para cancelar daños o acelerar acciones irreales?', opts: ['Skill','PG','FairPlay','BJ'], c: 'B' },
  /* 63 */ { q: '¿Un jugador usa conocimiento de mecánicas del servidor (ej: tiempos de respawn policial) para actuar IC. Qué es?', opts: ['Estrategia','MG','RDE','FairPlay'], c: 'B' },
  /* 64 */ { q: '¿Qué es "evadir rol pasivamente"?', opts: ['Desconectarse','No responder o alargar sin sentido','Huir','Matar'], c: 'B' },
  /* 65 */ { q: '¿Un criminal roba en plena avenida sin preocuparse por cámaras, testigos o tráfico. Qué incumple?', opts: ['MG','NVV','RDE','CJ'], c: 'C' },
  /* 66 */ { q: '¿Es válido usar excusas IC absurdas para evitar consecuencias (ej: "no siento dolor porque soy fuerte")?', opts: ['Sí','No, es PG','Depende','Solo mafias'], c: 'B' },
  /* 67 */ { q: '¿Un jugador se cambia de personaje para evitar consecuencias de uno anterior. Qué es?', opts: ['Correcto','Estrategia','Evasión de rol','FairPlay'], c: 'C' },
  /* 68 */ { q: '¿Qué ocurre si fuerzas a otro jugador a aceptar una acción sin posibilidad de respuesta?', opts: ['Buen rol','PG','FairPlay','DM'], c: 'B' },
  /* 69 */ { q: '¿Un EMS revive a alguien sin rolear heridas ni proceso médico. Qué es?', opts: ['Eficiencia','Correcto','Rol pobre / PG','FairPlay'], c: 'C' },
  /* 70 */ { q: '¿Qué es "metagaming pasivo"?', opts: ['No hablar','Usar info OOC sin decirlo explícitamente','Matar','Huir'], c: 'B' },
  /* 71 */ { q: '¿Un jugador actúa como si supiera que lo están apuntando sin haberlo visto. Qué es?', opts: ['Instinto','MG','NVV','Correcto'], c: 'B' },
  /* 72 */ { q: '¿Qué pasa si ignoras completamente heridas leves para seguir actuando normal?', opts: ['Correcto','NVV','PG leve','FairPlay'], c: 'C' },
  /* 73 */ { q: '¿Un policía usa la fuerza directamente sin escalar la situación. Qué es?', opts: ['Procedimiento','Abuso de rol','FairPlay','DM'], c: 'B' },
  /* 74 */ { q: '¿Un jugador usa binds para hacer múltiples acciones simultáneas irreales (ej: disparar + esposar instantáneo). Qué es?', opts: ['Skill','PG','Correcto','FairPlay'], c: 'B' },
  /* 75 */ { q: '¿Qué ocurre si un jugador ignora completamente las órdenes bajo amenaza real sin justificarlo?', opts: ['Correcto','NVV','BD','RK'], c: 'B' },
  /* 76 */ { q: '¿Un jugador usa rutas o zonas bug para escapar constantemente. Qué es?', opts: ['Estrategia','Abuso de bugs','Skill','FairPlay'], c: 'B' },
  /* 77 */ { q: '¿Qué es "romper continuidad del personaje"?', opts: ['Morir','Cambiar personalidad sin rol','Huir','Robar'], c: 'B' },
  /* 78 */ { q: '¿Un jugador prioriza siempre ganar sobre generar rol coherente. Qué es?', opts: ['Competitividad','NVV + PG','FairPlay','Correcto'], c: 'B' },
  /* 79 */ { q: '(Pregunta reservada)', opts: ['A','B','C','D'], c: 'B' },
];
